Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -76,3 +76,7 @@ jobs:
             docker run -d -p 5000:5000 nutzkiller/weather-app:${{ env.VERSION }} && \
             echo 'Deployment successful!' && \
             docker ps"
+      - name: Curl Test
+        run: |
+          echo "Testing the deployed application using curl..."
+          curl -sSf http://${{ secrets.EC2_HOST }}:5000 || { echo 'Curl test failed!'; exit 1; }
